<?php

/**
 * @file
 * Provides tests for ajax_defer.module
 */

/**
 * Implements hook_menu().
 */
function ajax_defer_test_menu() {

  $items = array();

  // @todo: handle includes.
  $items['ajax_defer/single'] = array(
    'page callback' => 'ajax_defer_test_single',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'ajax_defer_test.pages.inc',
  );

  $items['ajax_defer/multi'] = array(
    'page callback' => 'ajax_defer_test_multi',
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
    'file' => 'ajax_defer_test.pages.inc',
  );

  return $items;

}
